### ISSUE TITLE
User Story: Home Page

### ISSUE THREAD

**Issue by BilalEssafi1** [BilalEssafi1/ecosphere#12]
As a visitor, I can view posts on the home page, so I can learn more about what people on Ecosphere are posting about in relation to the topic sustainability and I can Sign Up in order to engage. 

Acceptance Criteria:

- The home page displays the recent posts, platform name and a Navigation bar allowing people to sign up or login
- Posts are displayed with images, descriptions, hashtags and bookmarks. 
- Posts are organised by creation date
- - Accessible to all users, logged in or not. 

Tasks:

- [x] Design and implement the homepage structure
- [x] Implement the posts page with organized posts
- [x] Ensurer mobile responsiveness and styling using Bootstrap and CSS
