### ISSUE TITLE
User Story: Sign-Up for Account

### ISSUE THREAD

**Issue by BilalEssafi1** [BilalEssafi1/ecosphere#13]
As a visitor, I can sign up for an account, so I can log in and create posts, follow people, like posts and bookmark posts that I like.

Acceptance Criteria

- User must provide all relevant data to create an account (username, password).
- Blank fields in the sign up form should not be accepted. 
- User should be redirected to sign in Form after successful account creation. 

Tasks: 

- [x] Create backend api for account creation
- [x] Design the sign-up page in the frontend with React
- [x] Implement validation for input fields
