### ISSUE TITLE
User Story: Edit Profile

### ISSUE THREAD

**Issue by BilalEssafi1** [BilalEssafi1/ecosphere#18]
As a logged-in user, I want to be able to update my profile information, change username and password. 

Acceptance Criteria:

- Users can update their profile information
- Users can change their username
- Users can update their password

Tasks:

- [x] Develop the profile edit form
- [x] Implement username and password change functionality
- [x] Implement delete account functionality
- [x] Ensure mobile responsiveness and styling using Bootstrap and CSS
